# html lang 语言
language: zh_CN

# Header 左上标题
navname: Reyes Meng's Blog

# navigatior items 引导项
nav:
  Posts: /archives
  Categories: /category
  Tags: /tag
  About: /about
  Music: https://reyesmeng2.github.io/

# favicon RSS图标
favicon: /image/RM.ico

# Profile
nickname: Reyes Meng

### this variable is MarkDown form.
description: Un estudiante universitario | Vivo en Qingdao | Русский новичок <br>正处于并将长期处于价格敏感型消费阶段
avatar: /image/ReyesMeng.jpg

# main menu navigation
## links key words should not be changed.
## Complete url after key words.
## Unused key can be commented out.
links:
  Blog: /archives
#  Category:
#  Tags:
#  Link:
#  Resume: /
#  Publish:
#  Trophy:
#  Gallary:
#  RSS:
#  AliPay:
#  ZhiHu: https://www.zhihu.com/people/sirice
#  LinkedIn:
#  FaceBook:
#  Twitter: https://twitter.com/98MENGMENG
#  Skype:
#  CodeSandBox:
#  CodePen:
#  Sketch:
#  Gitlab:
#  Dribble:
  Instagram: https://www.instagram.com/reyesmeng98/
#  Reddit:
  youtube: https://www.youtube.com/channel/UCDY-_ft2jebCkiDWENnq1Vg?view_as=subscriber
#  QQ:
#  Weibo:
#  WeChat:
  Github: https://github.com/CallMeMengMeng

# how links show: you have 2 choice--text or icon.
links_text_enable: false
links_icon_enable: true

# Post page
## Post_meta
post_meta_enable: true

post_author_enable: true
post_date_enable: true
post_category_enable: true
## Post copyright
post_copyright_enable: true

post_copyright_author_enable: true
post_copyright_permalink_enable: true
post_copyright_license_enable: true
post_copyright_license_text: Copyright (c) 2019 <a href="http://creativecommons.org/licenses/by-nc/4.0/">CC-BY-NC-4.0</a> LICENSE
post_copyright_slogan_enable: true
post_copyright_slogan_text: Vaya con <strong>Dios<strong>.
## toc
post_toc_enable: true

# Page
page_title_enable: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: MMMM D, YYYY
time_format: H:mm:ss

# stylesheets loaded in the <head>
stylesheets:
  - /css/style.css

# scripts loaded in the end of the body
scripts:
  - /js/script.js
  - /js/tocbot.min.js
    # tscanlin/tocbot: Build a table of contents from headings in an HTML document.
    # https://github.com/tscanlin/tocbot


# plugin functions
## Mathjax: Math Formula Support
## https://www.mathjax.org
mathjax:
  enable: true
  import: demand # global or demand
  ## global: all pages will load mathjax,this will degrade performance and some grammers may be parsed wrong.
  ## demand: Recommend option,if your post need fomula, you can declare 'mathjax: true' in Front-matter

aplayer:
  meting: true
